# Generated by Django 5.1.2 on 2024-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_discount_product_reorder_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing')], max_length=20, null=True),
        ),
    ]
