# Generated by Django 4.2.16 on 2024-12-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Log',
            fields=[
                ('action_type', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=255)),
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
