# Generated by Django 4.2.16 on 2024-11-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.jpg', max_length=2000, upload_to='Profile_Images'),
        ),
    ]
